---
- name: Install ntp time service
  apt:
    name: ntp
    state: present

- name: Configure ntp time service
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart and enable ntp service