---
- name: Install chrony time service
  yum:
    name: chrony
    state: present

- name: Configure chrony time service
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart and enable chrony service