---
- name: Install ClamAV
  apt:
    name: "{{ clamav_packages }}"
    state: present
  notify:
    - Start and enable clamav daemon service
    - Start and enable freshclam service

- name: Install and configure ClamAV unofficial signatures
  block:
  - name: Install ClamAV unofficial signatures
    package:
      name: clamav-unofficial-sigs
      state: present

  - name: Configure ClamAV unofficial signatures
    template:
      src: 00-clamav-unofficial-sigs.conf.j2
      dest: "{{ clamav_unofficial_sigs_conf_path }}"
      owner: root
      group: root
      mode: 0644
    notify:
      - Start and enable clamav daemon service
      - Start and enable freshclam service

  when: clamav_unofficial_sigs_enable | bool

- name: Install PyClamd
  pip:
    name: pyclamd
    state: present
    extra_args: --user

- name: Verify ClamAV apparmor definitions file exists
  stat:
    path: /etc/apparmor.d/usr.sbin.clamd
  register: clamav_apparmor_defs

- name: Replace ClamAV apparmor definitions
  command: /usr/sbin/apparmor_parser -r "{{ clamav_apparmor_defs.stat.path }}"
  changed_when: false
  when: clamav_apparmor_defs.stat is defined and clamav_apparmor_defs.stat.exists | bool
