---
# Temporary
enable_patch_files: false

enable_extra_mod: true
wootme:
  - COOP
  - NOOP
  - FOOT
  - HOOB
  - ROOB
  - COOT
  - XOOB
  - YOOP
  - BHFY
  - PEMX

kvm_cpu_randomization: true
kvm_cpu_randomization_extra: false
kvm_intel_cpu_names:
  - "i7-1185G7"
  - "i7-3770"
  - "i7-6700"
  - "i7-10700"
  - "i7-8700T"
  - "i5-10500T"
  - "i3-2120"
  - "i5-9400F"
  - "i7-10510U"
  - "i9-7940X"
  - "i9-10900KF"
  - "i9-10850K"
  - "i9-10900"
  - "i9-7900X"
  - "i7-6900K"
  - "i9-11900T"
  - "i9-10900KF"
  - "i9-9820X"
  - "i9-7920X"
  - "i9-9900K"
  - "i9-10900X"
  - "i9-7960X"
  - "i9-7900X"
  - "i9-9900KS"
  - "i9-9960X"
  - "i9-9900KF"
  - "i9-9900K"
  - "i9-9900X"
  - "i9-9940X"
  - "i9-7900X"

kvm_intel_cpuid_signatures:
  - "0x000206D6"
  - "0x000206D7"
  - "0x000206A5"
  - "0x000306A4"
  - "0x000306A9"
  - "0x000206C2"
  - "0x000106E5"
  - "0x00020652"
  - "0x000406F1"
  - "0x000306F2"
  - "0x000A0671"
  - "0x00050654"
  - "0x000A0655"
  - "0x000906ED"
  - "0x00050657"
  - "0x000906EC"

kvm_amd_cpu_names: []

hd_models:
  - "SAMSUNG MZ-76E120"
  - "SAMSUNG MZ-76E250"
  - "SAMSUNG MZ-76E500"
  - "SAMSUNG MZ-76E1T0"
  - "SAMSUNG MZ-76E2T0"
  - "SAMSUNG MZ-76E4T0"
  - "SAMSUNG MZ-VKV256"
  - "SAMSUNG MZ-VKV512"
  - "SAMSUNG MZ-V6E250"
  - "SAMSUNG MZ-V6E500"
  - "SAMSUNG MZ-V6E1T0"
  - "SAMSUNG MZ-V5P256BW"
  - "WD WDBA3V2500ANC-WRSN"
  - "WD WDBA3V5000ANC-WRSN"
  - "WD WDBA3V0010BNC-WRSN"
  - "SanDisk SD8SN8U-128G"
  - "SanDisk SD8SN8U-256G"
  - "SanDisk SD8SN8U-512G"
  - "SanDisk SD8SN8U-1T00"
  - "SanDisk SD8SB8U-128G"
  - "SanDisk SD8SB8U-256G"
  - "SanDisk SD8SB8U-512G"
  - "SanDisk SD8SB8U-1T00"
  - "KINGSTON SA400S37"
  - "KINGSTON SA400M8"
  - "KINGSTON SQ500S37"

dvd_models:
  - "HL-DT-ST WH1"
  - "HL-PV-SG WB4"
  - "HL-PQ-SV WB8"

qemu_version: 6.1.0
qemu_download_url: https://download.qemu.org
qemu_source_dir: /tmp
qemu_prefix_dir: /usr
qemu_libexec_dir: /usr/lib/qemu
qemu_localstate_dir: /var
qemu_bin_dir: /usr/bin/

qemu_apt_packages:
  - python3-pip
  - checkinstall
  - openbios-sparc
  - openbios-ppc
  - libssh2-1-dev
  - vde2
  - liblzo2-dev
  - libghc-gtk3-dev
  - libsnappy-dev
  - libbz2-dev
  - libxml2-dev
  - libvde-dev
  - debhelper
  - libusb-1.0-0-dev
  - libxen-dev
  - uuid-dev
  - xfslibs-dev
  - libjpeg-dev
  - libusbredirparser-dev
  - device-tree-compiler
  - texinfo
  - libbluetooth-dev
  - libbrlapi-dev
  - libcap-ng-dev
  - libcurl4-gnutls-dev
  - libfdt-dev
  - gnutls-dev
  - libiscsi-dev
  - libncurses5-dev
  - libnuma-dev
  - libcacard-dev
  - librados-dev
  - librbd-dev
  - libsasl2-dev
  - libseccomp-dev
  - libspice-server-dev
  - libaio-dev
  - libcap-dev
  - libattr1-dev
  - libpixman-1-dev
  - libgtk2.0-bin
  - libxml2-utils
  - systemtap-sdt-dev
  - uml-utilities
  - cpanminus
  - libjemalloc-dev
  - python3-sphinx-rtd-theme
  - libbpfcc-dev
  - libpmem-dev
  - libdaxctl-dev
qemu_pip_packages:
  - sphinx
  - sphinx-rtd-theme
  - ninja

qemu_build_config_options:
  - "prefix={{ qemu_prefix_dir }}"
  - "libexecdir={{ qemu_libexec_dir }}"
  - "localstatedir={{ qemu_localstate_dir }}"
  - "bindir={{ qemu_bin_dir }}"
  - "target-list=i386-softmmu,x86_64-softmmu,i386-linux-user,x86_64-linux-user"
  - enable-gnutls
  - enable-docs
  - enable-gtk
  - enable-vnc
  - enable-vnc-sasl
  - enable-vnc-png
  - enable-vnc-jpeg
  - enable-curl
  - enable-kvm
  - enable-linux-aio
  - enable-cap-ng
  - enable-vhost-net
  - enable-vhost-crypto
  - enable-spice
  - enable-usb-redir
  - enable-lzo
  - enable-snappy
  - enable-bzip2
  - enable-coroutine-pool
  - enable-libxml2
  - enable-jemalloc
  - enable-replication
  - enable-tools
  - enable-capstone
  #- enable-bpf

qemu_usb_models:
  - "DELL"
  - "HP"

seabios_repo_url: https://github.com/coreboot/seabios.git
seabios_source_dir: /tmp

libvirt_version: 7.7.0
libvirt_download_url: https://libvirt.org/sources
libvirt_source_dir: /tmp
libvirt_apt_packages:
  - apparmor-profiles
  - apparmor-profiles-extra
  - apparmor-utils
  - bash-completion
  - dmidecode
  - dnsmasq
  - ebtables
  - gnutls-bin
  - gnutls-dev
  - iptables
  - libapparmor-dev
  - libapparmor-perl
  - libdevmapper-dev
  - libglib2.0-dev
  - libnl-3-dev
  - libnl-route-3-dev
  - libnuma-dev
  - libosinfo-1.0-dev
  - libpciaccess-dev
  - librbd-dev
  - libreadline-dev
  - libsdl1.2-dev
  - libtirpc-dev
  - libxml2-dev
  - libxml2-utils
  - libyajl-dev
  - lvm2
  - mlocate
  - numactl
  - numad
  - python3-apparmor
  - python3-dev
  - python3-docutils
  - python3-pip
  - unzip
  - xsltproc
  - libnetcf-dev
  - cmake
  - libaudit-dev
  - libsanlock-dev
  - libssh-dev
  - libparted-dev
  - libdevmapper-dev
  - libbpfcc-dev

libvirt_pip_packages:
  - ipaddr
  - ninja
  - flake8
  - meson==0.57.2

libvirt_meson_core_options:
  - "buildtype=plain"
  - "auto-features=enabled"
libvirt_meson_build_options:
  - "system=true"
  - "driver_remote=enabled"
  - "driver_qemu=enabled"
  - "driver_libvirtd=enabled"
  - "qemu_group=libvirt"
  - "qemu_user=root"
  - "apparmor=enabled"
  - "apparmor_profiles=enabled"
  - "secdriver_apparmor=enabled"
  - "secdriver_selinux=disabled"
  - "bash_completion=auto"
  - "driver_esx=disabled"
  - "driver_hyperv=disabled"
  - "driver_openvz=disabled"
  - "driver_vbox=disabled"
  - "driver_vmware=disabled"
  - "driver_vz=disabled"
  - "driver_ch=disabled"
  - "driver_bhyve=disabled"
  - "driver_libxl=disabled"
  - "driver_lxc=disabled"
  - "openwsman=disabled"
  - "driver_interface=enabled"
  - "driver_network=enabled"
  - "selinux=disabled"
  - "fuse=disabled"
  - "init_script=systemd"
  - "sysctl_config=enabled"
  - "numad=enabled"
  - "numactl=enabled"
  - "polkit=enabled"
  - "curl=enabled"
  - "remote_default_mode=legacy"
  - "storage_fs=enabled"
  - "storage_lvm=enabled"
  - "storage_sheepdog=disabled"
  - "storage_zfs=disabled"
  - "storage_vstorage=disabled"
  - "storage_gluster=disabled"
  - "glusterfs=disabled"
  - "netcf=enabled"
  - "tls_priority=@LIBVIRT,SYSTEM"
  - "wireshark_dissector=disabled"
  - "libssh=enabled"
  - "libssh2=disabled"
  - "pm_utils=disabled"

erlang_repo_key: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
erlang_apt_packages:
  - parted
  - libyara3
  # Resolve configure: WARNING: Yara library not found
  - libyara-dev
  - erlang-dev
  - gperf
  - flex
  - bison
  - libaugeas-dev
  - libhivex-dev
  - supermin
  - ocaml-nox
  - libhivex-ocaml
  - genisoimage
  - libhivex-ocaml-dev
  - libmagic-dev
  - libjansson-dev
  - gnulib
  - jq
  - ocaml-findlib
  - erlang
  # Resolve configure: error: missing /usr/lib/jvm/default-java/bin/javac binary
  - default-jre-headless
  - default-jdk-headless
  # Resolve configure: WARNING: The Sleuth Kit library (libtsk) not found
  - libtsk-dev
libguestfs_repo_url: https://github.com/libguestfs/libguestfs.git
libguestfs_dir: /opt

virtmanager_apt_packages:
  - libgirepository1.0-dev
  - gtk-doc-tools
  - python3
  - python3-pip
  - gir1.2-govirt-1.0
  - libgovirt-dev
  - libgovirt-common
  - libgovirt2
  - gir1.2-rest-0.7
  - unzip
  - intltool
  - augeas-doc
  - ifupdown
  - wodim
  - cdrkit-doc
  - indicator-application
  - augeas-tools
  - radvd
  - auditd
  - systemtap
  - nfs-common
  - zfsutils
  - pm-utils
  - python-openssl-doc
  - samba
  - debootstrap
  - sharutils-doc
  - ssh-askpass
  - gnome-keyring
  - sharutils
  - spice-client-glib-usb-acl-helper
  - ubuntu-mono
  - x11-common
  - python-enum34
  - python3-gi
  - python3-gi-cairo
  - python3-pkg-resources
  - python3-libxml2
  - libxml2-utils
  - libxrandr2
  - libxrender1
  - libxshmfence1
  - libxtst6
  - libxv1
  - libyajl2
  - msr-tools
  - osinfo-db
  - python3-cairo
  - python3-cffi-backend
  - libxcb-present0
  - libxcb-render0
  - libxcb-shm0
  - libxcb-sync1
  - libxcb-xfixes0
  - libxcomposite1
  - libxcursor1
  - libxdamage1
  - libxenstore3.0
  - libxfixes3
  - libxft2
  - libxi6
  - libxinerama1
  - libxkbcommon0
  - libusbredirhost1
  - libusbredirparser1
  - libv4l-0
  - libv4lconvert0
  - libvisual-0.4-0
  - libvorbis0a
  - libvorbisenc2
  - libvte-2.91-0
  - libvte-2.91-common
  - libwavpack1
  - libwayland-client0
  - libwayland-cursor0
  - libwayland-egl1-mesa
  - libwayland-server0
  - libx11-xcb1
  - libxcb-dri2-0
  - libxcb-dri3-0
  - libsoup-gnome2.4-1
  - libsoup2.4-1
  - libspeex1
  - libspice-client-glib-2.0-8
  - libspice-client-gtk-3.0-5
  - libspice-server1
  - libtag1v5
  - libtag1v5-vanilla
  - libthai-data
  - libthai0
  - libtheora0
  - libtiff5
  - libtwolame0
  - libpython3-dev
  - librados2
  - libraw1394-11
  - librbd1
  - librdmacm1
  - librest-0.7-0
  - librsvg2-2
  - librsvg2-common
  - libsamplerate0
  - libsdl1.2debian
  - libshout3
  - libsndfile1
  - libpango-1.0-0
  - libpangocairo-1.0-0
  - libpangoft2-1.0-0
  - libpangoxft-1.0-0
  - libpciaccess0
  - libphodav-2.0-0
  - libphodav-2.0-common
  - libpixman-1-0
  - libproxy1v5
  - libpulse-mainloop-glib0
  - libpulse0
  - libgstreamer1.0-0
  - libgtk-3-0
  - libgtk-3-bin
  - libgtk-3-common
  - libgtk-vnc-2.0-0
  - libgudev-1.0-0
  - libgvnc-1.0-0
  - libharfbuzz0b
  - libibverbs1
  - libiec61883-0
  - libindicator3-7
  - libiscsi7
  - libjack-jackd2-0
  - libjbig0
  - libjpeg-turbo8
  - libjpeg8
  - libjson-glib-1.0-0
  - libjson-glib-1.0-common
  - liblcms2-2
  - libmp3lame0
  - libmpg123-0
  - libnetcf1
  - libnl-route-3-200
  - libnspr4
  - libnss3
  - libogg0
  - libopus0
  - liborc-0.4-0
  - libosinfo-1.0-0
  - libcairo-gobject2
  - libcairo2
  - libcdparanoia0
  - libcolord2
  - libcroco3
  - libcups2
  - libdatrie1
  - libdbusmenu-glib4
  - libdbusmenu-gtk3-4
  - libdconf1
  - libdv4
  - libegl-mesa0
  - libegl1
  - libepoxy0
  - libfdt1
  - libflac8
  - libfontconfig1
  - libgbm1
  - libgdk-pixbuf2.0-0
  - libgdk-pixbuf2.0-bin
  - libgdk-pixbuf2.0-common
  - libglapi-mesa
  - libglvnd0
  - libgraphite2-3
  - libgstreamer-plugins-base1.0-0
  - libgstreamer-plugins-good1.0-0
  - gtk-update-icon-cache
  - hicolor-icon-theme
  - humanity-icon-theme
  - ibverbs-providers
  - libaa1
  - libaio1
  - libappindicator3-1
  - libasound2
  - libasound2-data
  - libasyncns0
  - libatk-bridge2.0-0
  - libatk1.0-0
  - libatk1.0-data
  - libatspi2.0-0
  - libaugeas0
  - libavahi-client3
  - libavahi-common-data
  - libavahi-common3
  - libavc1394-0
  - libbluetooth3
  - libcaca0
  - libcacard0
  - gir1.2-atk-1.0
  - gir1.2-freedesktop
  - gir1.2-gdkpixbuf-2.0
  - gir1.2-gtk-3.0
  - gir1.2-gtk-vnc-2.0
  - gir1.2-libosinfo-1.0
  - gir1.2-pango-1.0
  - gir1.2-spiceclientglib-2.0
  - gir1.2-spiceclientgtk-3.0
  - gir1.2-vte-2.91
  - glib-networking
  - glib-networking-common
  - glib-networking-services
  - gsettings-desktop-schemas
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-x
  - adwaita-icon-theme
  - at-spi2-core
  - augeas-lenses
  - cpu-checker
  - dconf-gsettings-backend
  - dconf-service
  - fontconfig
  - fontconfig-config
  - fonts-dejavu-core
  - genisoimage
  - gir1.2-appindicator3-0.1
  - gir1.2-secret-1
  - gobject-introspection
  - intltool
  - pkg-config
  - libxml2-dev
  - libxslt-dev
  - python3-dev
  - gir1.2-gtk-vnc-2.0
  - gir1.2-spiceclientgtk-3.0
  - libgtk-3-dev
  - mlocate
  - gir1.2-gtksource-4
  - libgtksourceview-4-0
  - libgtksourceview-4-common
  - python3-ntlm-auth
  - libpython3-stdlib
  - libbrlapi-dev
  - libgirepository1.0-dev
  - python3-testresources

virtmanager_pip_packages:
  - tqdm
  - requests
  - six
  - urllib3
  - ipaddr
  - ipaddress
  - idna
  - dbus-python
  - certifi
  - lxml
  - cryptography
  - pyOpenSSL
  - chardet
  - asn1crypto
  - pycairo
  - PySocks
  - PyGObject

virtmanager_source_code_dir: /tmp/virt-manager

libvirt_glib_version: 4.0.0
libvirt_glib_url: https://libvirt.org/sources/glib


virtmanager_repo_url: https://github.com/virt-manager/virt-manager.git

cockpit_enable: true
cockpit_packages:
  - libsystemd-dev
  - libjson-glib-dev
  - libkrb5-dev
  - libpolkit-agent-1-dev
  - libssh-dev
  - libpam0g-dev
  - libpcp3-dev
  - libpcp-pmda3-dev
  - libpcp-import1-dev
  - nodejs
cockpit_repo_url: https://github.com/cockpit-project/cockpit.git
cockpit_machines_repo_url: https://github.com/cockpit-project/cockpit-machines.git
cockpit_dir: /usr
cockpit_temp_dir: /tmp