---
- name: Install and configure MaxMindDB
  block:
    - name: Add MaxMind repository
      apt_repository:
        repo: "ppa:maxmind/ppa"
        codename: "{{ ansible_distribution_release }}"

    - name: Install MaxMind packages
      apt:
        name: 
          - libmaxminddb-dev
          - geoipupdate
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Configure MaxMind update
      template:
        src: GeoIP.conf.j2
        dest: "{{ maxminddb_conf_dir }}/GeoIP.conf"
        create: true
  when:
    - maxminddb_account_id is defined and maxminddb_account_id | bool
    - maxminddb_license_key is defined and maxminddb_license_key | bool
    - maxminddb_edition_ids is defined and maxminddb_edition_ids | bool
