---
#####################################################
# OS Defaults
#####################################################
os_sudo_logfile_path: /var/log/sudo.log

use_motd_message: true

#####################################################
# Section 1 - Filesystem Configuation Variables
#####################################################
cis_disable_cramfs: true
cis_disable_freevxfs: true
cis_disable_jffs2: true
cis_disable_hfs: true
cis_disable_hfsplus: true
cis_disable_vfat: false
cis_disable_squashfs: true
cis_disable_udf: true
cis_disable_automounting: true
cis_disable_usb: false

cis_disable_xinetd: true
cis_disable_openbsdinted: true
cis_disable_xwindow: false
cis_disable_rsyncd: true
cis_disable_avahi: true
cis_disable_snmpd: true
cis_disable_httpproxy: true
cis_disable_smb: true
cis_disable_imappop3: true
cis_disable_http: true
cis_disable_ftp: true
cis_disable_dns: true
cis_disable_nfs: true
cis_disable_rpc: true
cis_disable_ldap: true
cis_disable_dhcp: true
cis_disable_cups: true
cis_disable_nis: true
cis_disable_mta: true
cis_disable_telnet: true
cis_disable_client_rsh: true
cis_disable_client_talk: true
cis_disable_client_telnet: true
cis_disable_client_ldap: true
cis_disable_client_rpc: true

#####################################################
# Section 2 - Services
#####################################################
xorg_packages:
  - xserver-xorg
  - xserver-xorg-core
  - xserver-xorg-driver-all
  - xserver-xorg-input-all
  - xserver-xorg-input-evtouch
  - xserver-xorg-input-libinput
  - xserver-xorg-input-wacom
  - xserver-xorg-legacy
  - xserver-xorg-video-all
  - xserver-xorg-video-amdgpu
  - xserver-xorg-video-ati
  - xserver-xorg-video-fbdev
  - xserver-xorg-video-intel
  - xserver-xorg-video-mach64
  - xserver-xorg-video-modesetting
  - xserver-xorg-video-nouveau
  - xserver-xorg-video-qxl
  - xserver-xorg-video-r128
  - xserver-xorg-video-radeon
  - xserver-xorg-video-vesa
  - xserver-xorg-video-vmware


#####################################################
# Section 3 Variables
#####################################################

#####################################################
# Section 4 - Logging and Auditing
#####################################################
cis_audit_rules_path: /etc/audit/rules.d
cis_auditd_backlog_limit: 8192
cis_auditd_max_log_file:
cis_auditd_max_log_file_action: keep_logs
cis_auditd_space_left_action: email
cis_auditd_action_mail_acct: root
cis_auditd_admin_space_left_action:
cis_priviliged_auditd_rules: []

#####################################################
# Section 5 Access, Authentication and Authorization
#####################################################
cis_sshd_config:
  log_level: INFO
  x11forwarding: 'no'
  max_auth_tries: 4
  ignore_rhosts: 'yes'
  host_based_auth: 'no'
  permit_root_login: 'no'
  permit_empty_password: 'no'
  permit_user_environment: 'no'
  client_alive_interval: 300
  client_alive_count_max: 0
  login_grace_time: 60
  banner: /etc/issue.net
  use_pam: 'yes'
  allow_tcp_forwarding: 'no'
  max_startups: 10:30:60
  max_sessions: 4
  configure_ssh_users_groups: true
  allow_users:
    - admin
    - devops
    - vagrant
  deny_users: []
  allow_groups: []
  deny_groups: []
  ciphers:
    - "chacha20-poly1305@openssh.com"
    - "aes256-gcm@openssh.com,aes128-gcm@openssh.com"
    - "aes256-ctr,aes192-ctr,aes128-ctr"
  macs:
    - "hmac-sha2-512-etm@openssh.com"
    - "hmac-sha2-256-etm@openssh.com"
    - "hmac-sha2-512,hmac-sha2-256"
  kexalgorithms:
    - "curve25519-sha256"
    - "curve25519-sha256@libssh.org"
    #- "diffie-hellmangroup14-sha256" Unsupported
    - "diffie-hellman-group16-sha512"
    - "diffie-hellman-group18-sha512"
    - "ecdh-sha2-nistp521"
    - "ecdh-sha2-nistp384"
    - "ecdh-sha2-nistp256"
    #- "diffiehellman-group-exchange-sha256" Unspported

cis_shadow_params:
  pass_max_days: 365
  pass_min_days: 7
  pass_warn_age: 7
  inactive_days: 30

cis_default_user_mask: "027"
cis_default_user_shell_timeout: 900
