---
mongodb_version: 5.0
mongodb_repo_key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"

mongodb_db_main_path: /data
mongodb_db_paths:
  - "{{ mongodb_db_main_path }}/db"
  - "{{ mongodb_db_main_path }}/configdb"
