- name: Flush IPv4 route table
  sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: true

- name: Flush IPv6 route table
  sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: true
