---
livepatch_enable: false
livepatch_apitoken:


packages:
  - apparmor-utils
  - autoconf
  - automake
  - binutils-dev
  - bison
  - cabextract
  - checkinstall
  - curl
  - exiftool
  - flex
  - gcc
  - g++
  - geoip-database
  - git
  - graphviz
  - jq
  - libarchive-dev
  - libcap2-bin
  - libconfig-dev
  - libdate-simple-perl
  - libdatetime-perl
  - libdbd-mysql-perl
  - libfuzzy-dev
  - libgeoip-dev
  - libglib2.0-dev
  - libjansson-dev
  - libjpeg-dev
  - libldns-dev
  - libmagic1
  - libmagic-dev
  - libpcap-dev
  - libpcre3-dev
  - libpq-dev
  - libssl-dev
  - libtool
  - lzip
  - make
  - mono-utils
  - net-tools
  - numactl
  #- openjdk-11-jdk-headless
  #- openjdk-8-jdk-headless
  - openvpn
  - p7zip-full
  - pkg-config
  - privoxy
  - psmisc
  - python3
  - python3-dev
  - python3-pil
  - python3-pip
  - python3-pydot
  - python3-pyelftools
  - rar
  - software-properties-common
  - sqlite3
  - ssdeep
  - subversion
  - sysfsutils
  - tcpdump
  - tmux
  - unace-nonfree
  - unrar
  - unzip
  - upx-ucl
  - uthash-dev
  - uwsgi
  - uwsgi-plugin-python3
  - wget
  - wireguard
  - wkhtmltopdf
  - xfonts-100dpi
  - xvfb
  - zip
  - zlib1g-dev

utf_locales:
  - "aa_DJ.UTF-8"
  - "aa_ER"
  - "aa_ER@saaho"
  - "aa_ET"
  - "af_ZA.UTF-8"
  - "agr_PE"
  - "ak_GH"
  - "am_ET"
  - "an_ES.UTF-8"
  - "anp_IN"
  - "ar_AE.UTF-8"
  - "ar_BH.UTF-8"
  - "ar_DZ.UTF-8"
  - "ar_EG.UTF-8"
  - "ar_IN"
  - "ar_IQ.UTF-8"
  - "ar_JO.UTF-8"
  - "ar_KW.UTF-8"
  - "ar_LB.UTF-8"
  - "ar_LY.UTF-8"
  - "ar_MA.UTF-8"
  - "ar_OM.UTF-8"
  - "ar_QA.UTF-8"
  - "ar_SA.UTF-8"
  - "ar_SD.UTF-8"
  - "ar_SS"
  - "ar_SY.UTF-8"
  - "ar_TN.UTF-8"
  - "ar_YE.UTF-8"
  - "as_IN"
  - "ast_ES.UTF-8"
  - "ayc_PE"
  - "az_AZ"
  - "az_IR"
  - "be_BY.UTF-8"
  - "be_BY@latin"
  - "bem_ZM"
  - "ber_DZ"
  - "ber_MA"
  - "bg_BG.UTF-8"
  - "bhb_IN.UTF-8"
  - "bho_IN"
  - "bho_NP"
  - "bi_VU"
  - "bn_BD"
  - "bn_IN"
  - "bo_CN"
  - "bo_IN"
  - "br_FR.UTF-8"
  - "brx_IN"
  - "bs_BA.UTF-8"
  - "byn_ER"
  - "ca_AD.UTF-8"
  - "ca_ES.UTF-8"
  - "ca_ES@valencia"
  - "ca_FR.UTF-8"
  - "ca_IT.UTF-8"
  - "ce_RU"
  - "chr_US"
  - "ckb_IQ"
  - "cmn_TW"
  - "crh_UA"
  - "cs_CZ.UTF-8"
  - "csb_PL"
  - "cv_RU"
  - "cy_GB.UTF-8"
  - "da_DK.UTF-8"
  - "de_AT.UTF-8"
  - "de_BE.UTF-8"
  - "de_CH.UTF-8"
  - "de_DE.UTF-8"
  - "de_IT.UTF-8"
  - "de_LI.UTF-8"
  - "de_LU.UTF-8"
  - "doi_IN"
  - "dsb_DE"
  - "dv_MV"
  - "dz_BT"
  - "el_CY.UTF-8"
  - "el_GR.UTF-8"
  - "en_AG"
  - "en_AU.UTF-8"
  - "en_BW.UTF-8"
  - "en_CA.UTF-8"
  - "en_DK.UTF-8"
  - "en_GB.UTF-8"
  - "en_HK.UTF-8"
  - "en_IE.UTF-8"
  - "en_IL"
  - "en_IN"
  - "en_NG"
  - "en_NZ.UTF-8"
  - "en_PH.UTF-8"
  - "en_SC.UTF-8"
  - "en_SG.UTF-8"
  - "en_US.UTF-8"
  - "en_ZA.UTF-8"
  - "en_ZM"
  - "en_ZW.UTF-8"
  - "eo"
  - "eo_US.UTF-8"
  - "es_AR.UTF-8"
  - "es_BO.UTF-8"
  - "es_CL.UTF-8"
  - "es_CO.UTF-8"
  - "es_CR.UTF-8"
  - "es_CU"
  - "es_DO.UTF-8"
  - "es_EC.UTF-8"
  - "es_ES.UTF-8"
  - "es_GT.UTF-8"
  - "es_HN.UTF-8"
  - "es_MX.UTF-8"
  - "es_NI.UTF-8"
  - "es_PA.UTF-8"
  - "es_PE.UTF-8"
  - "es_PR.UTF-8"
  - "es_PY.UTF-8"
  - "es_SV.UTF-8"
  - "es_US.UTF-8"
  - "es_UY.UTF-8"
  - "es_VE.UTF-8"
  - "et_EE.UTF-8"
  - "eu_ES.UTF-8"
  - "eu_FR.UTF-8"
  - "fa_IR"
  - "ff_SN"
  - "fi_FI.UTF-8"
  - "fil_PH"
  - "fo_FO.UTF-8"
  - "fr_BE.UTF-8"
  - "fr_CA.UTF-8"
  - "fr_CH.UTF-8"
  - "fr_FR.UTF-8"
  - "fr_LU.UTF-8"
  - "fur_IT"
  - "fy_DE"
  - "fy_NL"
  - "ga_IE.UTF-8"
  - "gd_GB.UTF-8"
  - "gez_ER"
  - "gez_ER@abegede"
  - "gez_ET"
  - "gez_ET@abegede"
  - "gl_ES.UTF-8"
  - "gu_IN"
  - "gv_GB.UTF-8"
  - "ha_NG"
  - "hak_TW"
  - "he_IL.UTF-8"
  - "hi_IN"
  - "hif_FJ"
  - "hne_IN"
  - "hr_HR.UTF-8"
  - "hsb_DE.UTF-8"
  - "ht_HT"
  - "hu_HU.UTF-8"
  - "hy_AM"
  - "ia_FR"
  - "id_ID.UTF-8"
  - "ig_NG"
  - "ik_CA"
  - "is_IS.UTF-8"
  - "it_CH.UTF-8"
  - "it_IT.UTF-8"
  - "iu_CA"
  - "ja_JP.UTF-8"
  - "ka_GE.UTF-8"
  - "kab_DZ"
  - "kk_KZ.UTF-8"
  - "kl_GL.UTF-8"
  - "km_KH"
  - "kn_IN"
  - "ko_KR.UTF-8"
  - "kok_IN"
  - "ks_IN"
  - "ks_IN@devanagari"
  - "ku_TR.UTF-8"
  - "kw_GB.UTF-8"
  - "ky_KG"
  - "lb_LU"
  - "lg_UG.UTF-8"
  - "li_BE"
  - "li_NL"
  - "lij_IT"
  - "ln_CD"
  - "lo_LA"
  - "lt_LT.UTF-8"
  - "lv_LV.UTF-8"
  - "lzh_TW"
  - "mag_IN"
  - "mai_IN"
  - "mai_NP"
  - "mfe_MU"
  - "mg_MG.UTF-8"
  - "mhr_RU"
  - "mi_NZ.UTF-8"
  - "miq_NI"
  - "mjw_IN"
  - "mk_MK.UTF-8"
  - "ml_IN"
  - "mn_MN"
  - "mni_IN"
  - "mnw_MM"
  - "mr_IN"
  - "ms_MY.UTF-8"
  - "mt_MT.UTF-8"
  - "my_MM"
  - "nan_TW"
  - "nan_TW@latin"
  - "nb_NO.UTF-8"
  - "nds_DE"
  - "nds_NL"
  - "ne_NP"
  - "nhn_MX"
  - "niu_NU"
  - "niu_NZ"
  - "nl_AW"
  - "nl_BE.UTF-8"
  - "nl_NL.UTF-8"
  - "nn_NO.UTF-8"
  - "nr_ZA"
  - "nso_ZA"
  - "oc_FR.UTF-8"
  - "om_ET"
  - "om_KE.UTF-8"
  - "or_IN"
  - "os_RU"
  - "pa_IN"
  - "pa_PK"
  - "pap_AW"
  - "pap_CW"
  - "pl_PL.UTF-8"
  - "ps_AF"
  - "pt_BR.UTF-8"
  - "pt_PT.UTF-8"
  - "quz_PE"
  - "raj_IN"
  - "ro_RO.UTF-8"
  - "ru_RU.UTF-8"
  - "ru_UA.UTF-8"
  - "rw_RW"
  - "sa_IN"
  - "sah_RU"
  - "sat_IN"
  - "sc_IT"
  - "sd_IN"
  - "sd_IN@devanagari"
  - "sd_PK"
  - "se_NO"
  - "sgs_LT"
  - "shn_MM"
  - "shs_CA"
  - "si_LK"
  - "sid_ET"
  - "sk_SK.UTF-8"
  - "sl_SI.UTF-8"
  - "sm_WS"
  - "so_DJ.UTF-8"
  - "so_ET"
  - "so_KE.UTF-8"
  - "so_SO.UTF-8"
  - "sq_AL.UTF-8"
  - "sq_MK"
  - "sr_ME"
  - "sr_RS"
  - "sr_RS@latin"
  - "ss_ZA"
  - "st_ZA.UTF-8"
  - "sv_FI.UTF-8"
  - "sv_SE.UTF-8"
  - "sw_KE"
  - "sw_TZ"
  - "szl_PL"
  - "ta_IN"
  - "ta_LK"
  - "tcy_IN.UTF-8"
  - "te_IN"
  - "tg_TJ.UTF-8"
  - "th_TH.UTF-8"
  - "the_NP"
  - "ti_ER"
  - "ti_ET"
  - "tig_ER"
  - "tk_TM"
  - "tl_PH.UTF-8"
  - "tn_ZA"
  - "to_TO"
  - "tpi_PG"
  - "tr_CY.UTF-8"
  - "tr_TR.UTF-8"
  - "ts_ZA"
  - "tt_RU"
  - "tt_RU@iqtelif"
  - "ug_CN"
  - "ug_CN@latin"
  - "uk_UA.UTF-8"
  - "unm_US"
  - "ur_IN"
  - "ur_PK"
  - "uz_UZ.UTF-8"
  - "uz_UZ@cyrillic"
  - "ve_ZA"
  - "vi_VN"
  - "wa_BE.UTF-8"
  - "wae_CH"
  - "wal_ET"
  - "wo_SN"
  - "xh_ZA.UTF-8"
  - "yi_US.UTF-8"
  - "yo_NG"
  - "yue_HK"
  - "yuw_PG"
  - "zh_CN.UTF-8"
  - "zh_HK.UTF-8"
  - "zh_SG.UTF-8"
  - "zh_TW.UTF-8"
  - "zu_ZA.UTF-8"
language_packages:
  - "language-pack-af"
  - "language-pack-am"
  - "language-pack-an"
  - "language-pack-ar"
  - "language-pack-as"
  - "language-pack-ast"
  - "language-pack-az"
  - "language-pack-be"
  - "language-pack-bg"
  - "language-pack-bn"
  - "language-pack-br"
  - "language-pack-bs"
  - "language-pack-ca"
  - "language-pack-ckb"
  - "language-pack-crh"
  - "language-pack-cs"
  - "language-pack-cy"
  - "language-pack-da"
  - "language-pack-de"
  - "language-pack-dz"
  - "language-pack-el"
  - "language-pack-en"
  - "language-pack-eo"
  - "language-pack-es"
  - "language-pack-et"
  - "language-pack-eu"
  - "language-pack-fa"
  - "language-pack-fi"
  - "language-pack-fr"
  - "language-pack-fur"
  - "language-pack-ga"
  - "language-pack-gd"
  - "language-pack-gl"
  - "language-pack-gu"
  - "language-pack-he"
  - "language-pack-hi"
  - "language-pack-hr"
  - "language-pack-hu"
  - "language-pack-ia"
  - "language-pack-id"
  - "language-pack-is"
  - "language-pack-it"
  - "language-pack-ja"
  - "language-pack-ka"
  - "language-pack-kk"
  - "language-pack-km"
  - "language-pack-kn"
  - "language-pack-ko"
  - "language-pack-ku"
  - "language-pack-lt"
  - "language-pack-lv"
  - "language-pack-mk"
  - "language-pack-ml"
  - "language-pack-mr"
  - "language-pack-ms"
  - "language-pack-my"
  - "language-pack-nb"
  - "language-pack-nds"
  - "language-pack-ne"
  - "language-pack-nl"
  - "language-pack-nn"
  - "language-pack-oc"
  - "language-pack-or"
  - "language-pack-pa"
  - "language-pack-pl"
  - "language-pack-pt"
  - "language-pack-ro"
  - "language-pack-ru"
  - "language-pack-si"
  - "language-pack-sk"
  - "language-pack-sl"
  - "language-pack-sq"
  - "language-pack-sr"
  - "language-pack-sv"
  - "language-pack-szl"
  - "language-pack-ta"
  - "language-pack-te"
  - "language-pack-tg"
  - "language-pack-th"
  - "language-pack-tr"
  - "language-pack-ug"
  - "language-pack-uk"
  - "language-pack-vi"
  - "language-pack-xh"
  - "language-pack-zh-hans"
  - "language-pack-zh-hant"
